assert_spec x86

set use_vfs_ram 0
set use_part_block 1

proc block_partition { } { return 0 }

proc block_provider_name { } { return vfs_block }

proc block_provider { } {
	return "
	<start name=\"vfs_block\" caps=\"2000\">
		<resource name=\"RAM\" quantum=\"1100M\"/>
		<provides> <service name=\"Block\"/> </provides>
		<config>
			<vfs>
				<ram/>
				<import>
					<zero name=\"block_file\" size=\"1G\"/>
				</import>
			</vfs>
			<default-policy file=\"/block_file\" block_size=\"512\" writeable=\"yes\"/>
		</config>
		<route>
			<any-service> <parent/> </any-service>
		</route>
	</start>
"
}

append build_components {
	lib/vfs_import
	server/vfs_block
}

source ${genode_dir}/repos/world/run/fio.inc

append qemu_args " -nographic "
append qemu_args " -m 2048 "

run_genode_until {.*child "sequence" exited with exit value 0.*\n} 1200
