if {![info exists ::env(GENODE_FIO_SETUP_COMPLETE)]} {
	puts "This run-script writes to the block-device. Check the configured"
		puts "partition and set the enviornment variable GENODE_FIO_SETUP_COMPLETE"
		puts "to continue."
		exit 1
}

assert_spec x86

set use_vfs_ram 0
set use_part_block 1

proc block_partition { } {
	if {[have_include power_on/qemu]} {
		return 1
	} else {
		return 8
	}
}

proc block_provider_name { } { return ahci }

proc block_provider { } {
	return "
	<start name=\"ahci\" caps=\"120\">
		<resource name=\"RAM\" quantum=\"24M\"/>
		<provides> <service name=\"Block\"/> </provides>
		<config>
			<default-policy device=\"2\" writeable=\"yes\"/>
		</config>
		<route>
			<service name=\"Platform\"><child name=\"platform\"/> </service>
			<service name=\"Timer\">   <child name=\"timer\"/>    </service>
			<service name=\"CPU\">     <parent/>                  </service>
			<service name=\"ROM\">     <parent/>                  </service>
			<service name=\"PD\">      <parent/>                  </service>
			<service name=\"LOG\">     <parent/>                  </service>
		</route>
	</start>\n"
}

append build_components {
	driver/ahci
}

source ${genode_dir}/repos/world/run/fio.inc

append qemu_args " -nographic "
append qemu_args " -m 2048 "
append qemu_args " -device ahci,id=ahci "
append qemu_args " -drive id=disk,file=bin/nvme.raw,format=raw,if=none "
append qemu_args " -device ide-hd,drive=disk,bus=ahci.0 "
append qemu_args " -drive id=cd,file=[run_dir]/../fio_ahci.iso,if=none,media=cdrom "
append qemu_args " -device ide-cd,drive=cd,bus=ahci.1 "
append qemu_args " -boot d "


run_genode_until {.*child "sequence" exited with exit value 0.*\n} 1200
