set build_components { test/sdl2 }

set app_config {
	<start name="test-sdl2" caps="128">
		<resource name="RAM" quantum="48M"/>
		<config ld_verbose="yes">
			<vfs> <dir name="dev"> <log/> </dir> </vfs>
			<libc stdout="/dev/log"/>
		</config>
	</start>}

set boot_modules {
	test-sdl2
	libc.lib.so libm.lib.so zlib.lib.so vfs.lib.so sdl2.lib.so
	expat.lib.so egl.lib.so glapi.lib.so mesa.lib.so stdcxx.lib.so
	libdrm.lib.so vfs_gpu.lib.so
}

source ${genode_dir}/repos/world/run/gui_app.inc
